sudo: required
services:
  - docker

language: generic

before_install:
  - docker build -t sirajrkhan/e2e -f Dockerfile.dev .

script:
  - docker run -e CI=true sirajrkhan/e2e npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-581985205712"
  bucket_path: "docker"
  on:
    branch: master
    
  # Generate these keys in IAM @ AWS .... and then config @ Travis settings
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 
